#!/bin/bash
# The interpreter used to execute the script

#“#SBATCH” directives that convey submission options:

#SBATCH --job-name=example_job
#SBATCH --mail-type=BEGIN,END
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=32000m 
#SBATCH --time=10:00
#SBATCH --account=eecs570s001w22_class
#SBATCH --partition=gpu
#SBATCH --gpus-per-node=1

if [ "$#" -ne 1 ] || { [ "$1" != 16 ] && [ "$1" != 32 ] && [ "$1" != 64 ]; }; then
    echo "Usage: sbatch run_tests [16 | 32 | 64]"
    exit 1
fi

# time _build/GCN $1
time ./pa1_gpu_gl $1